//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ServiceEmpresa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SL_WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Empresa))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Ex {
            get {
                return this.ExField;
            }
            set {
                if ((object.ReferenceEquals(this.ExField, value) != true)) {
                    this.ExField = value;
                    this.RaisePropertyChanged("Ex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEmpresa.IEmpresa")]
    public interface IEmpresa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/Add", ReplyAction="http://tempuri.org/IEmpresa/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServiceEmpresa.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PL_MVC.ServiceEmpresa.Result Add(ML.Empresa empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/Add", ReplyAction="http://tempuri.org/IEmpresa/AddResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceEmpresa.Result> AddAsync(ML.Empresa empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/Update", ReplyAction="http://tempuri.org/IEmpresa/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServiceEmpresa.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PL_MVC.ServiceEmpresa.Result Update(ML.Empresa empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/Update", ReplyAction="http://tempuri.org/IEmpresa/UpdateResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceEmpresa.Result> UpdateAsync(ML.Empresa empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/Delete", ReplyAction="http://tempuri.org/IEmpresa/DeleteResponse")]
        PL_MVC.ServiceEmpresa.Result Delete(int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/Delete", ReplyAction="http://tempuri.org/IEmpresa/DeleteResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceEmpresa.Result> DeleteAsync(int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/GetAll", ReplyAction="http://tempuri.org/IEmpresa/GetAllResponse")]
        PL_MVC.ServiceEmpresa.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/GetAll", ReplyAction="http://tempuri.org/IEmpresa/GetAllResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceEmpresa.Result> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/GetById", ReplyAction="http://tempuri.org/IEmpresa/GetByIdResponse")]
        PL_MVC.ServiceEmpresa.Result GetById(int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/GetById", ReplyAction="http://tempuri.org/IEmpresa/GetByIdResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceEmpresa.Result> GetByIdAsync(int IdEmpresa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpresaChannel : PL_MVC.ServiceEmpresa.IEmpresa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpresaClient : System.ServiceModel.ClientBase<PL_MVC.ServiceEmpresa.IEmpresa>, PL_MVC.ServiceEmpresa.IEmpresa {
        
        public EmpresaClient() {
        }
        
        public EmpresaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpresaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL_MVC.ServiceEmpresa.Result Add(ML.Empresa empresa) {
            return base.Channel.Add(empresa);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceEmpresa.Result> AddAsync(ML.Empresa empresa) {
            return base.Channel.AddAsync(empresa);
        }
        
        public PL_MVC.ServiceEmpresa.Result Update(ML.Empresa empresa) {
            return base.Channel.Update(empresa);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceEmpresa.Result> UpdateAsync(ML.Empresa empresa) {
            return base.Channel.UpdateAsync(empresa);
        }
        
        public PL_MVC.ServiceEmpresa.Result Delete(int IdEmpresa) {
            return base.Channel.Delete(IdEmpresa);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceEmpresa.Result> DeleteAsync(int IdEmpresa) {
            return base.Channel.DeleteAsync(IdEmpresa);
        }
        
        public PL_MVC.ServiceEmpresa.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceEmpresa.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public PL_MVC.ServiceEmpresa.Result GetById(int IdEmpresa) {
            return base.Channel.GetById(IdEmpresa);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceEmpresa.Result> GetByIdAsync(int IdEmpresa) {
            return base.Channel.GetByIdAsync(IdEmpresa);
        }
    }
}
